
backend:
  name: git-gateway
  branch: master 

site_url: https://woodmancustomconstruction.netlify.app/
logo_url: https://woodmancustomconstruction.netlify.app/assets/img/logo.png 

media_folder: "assets/work"
public_folder: "/assets/work"

collections:
  - name: "project"
    label: "Project"
    folder: "content/project"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Type", name: "type", widget: "select", options: ['Bathroom', 'Deck', 'Fireplace', 'Cabinetry'] }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Gallery", name: "gallery", widget: "image", choose_url: false, media_library: {config: {multiple: true, max_files: 999}},
          hint: "First image will be the cover image." }