backend:
  name: git-gateway
  branch: main  # Ensure this matches your default branch

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }