backend:
  name: git-gateway
  branch: master 

site_url: https://woodmancustomconstruction.netlify.app/

media_folder: "assets/work"
public_folder: "/assets/work"
media_library:
  name: cloudinary
  config:
    cloud_name: dje4uyqoo
    api_key: 831313561675293

collections:
  - name: "bathroom-project"
    label: "Bathroom Project"
    folder: "content/project-bathroom"
    create: true
    slug: "bathroom_project{{project-num}}"
    summary: '{{title}}(#{{project-num}})'
    description: >
      Please ensure that project numbers are sequential, with no gaps. 
      Currently, there is no way to safely remove a project. If you need to remove a project, either replace an existing project's content with a new one or contact Nathan for assistance.
    fields:
      - { label: "Project Number", name: "project-num", widget: "number", value_type: "int", min: 1 }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - label: "Gallery"
        name: "gallery"
        widget: "image"
        hint: "First image will be cover image."
        allow_multiple: true
        choose_url: true
        media_library:
          config:
            multiple: true
  - name: "cabinetry-project"
    label: "Cabinetry Project"
    folder: "content/project-cabinetry"
    create: true
    slug: "cabinetry_project{{project-num}}"
    summary: '{{title}}(#{{project-num}})'
    description: >
      Please ensure that project numbers are sequential, with no gaps. 
      Currently, there is no way to safely remove a project. If you need to remove a project, either replace an existing project's content with a new one or contact Nathan for assistance.
    fields:
      - { label: "Project Number", name: "project-num", widget: "number", value_type: "int", min: 1 }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - label: "Gallery"
        name: "gallery"
        widget: "image"
        hint: "First image will be cover image."
        allow_multiple: true
        choose_url: true
        media_library:
          config:
            multiple: true
  - name: "fireplace-project"
    label: "Fireplace Project"
    folder: "content/project-fireplace"
    create: true
    slug: "fireplace_project{{project-num}}"
    summary: '{{title}}(#{{project-num}})'
    description: >
      Please ensure that project numbers are sequential, with no gaps. 
      Currently, there is no way to safely remove a project. If you need to remove a project, either replace an existing project's content with a new one or contact Nathan for assistance.
    fields:
      - { label: "Project Number", name: "project-num", widget: "number", value_type: "int", min: 1 }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - label: "Gallery"
        name: "gallery"
        widget: "image"
        hint: "First image will be cover image."
        allow_multiple: true
        choose_url: true
        media_library:
          config:
            multiple: true
  - name: "deck-project"
    label: "Deck Project"
    folder: "content/project-deck"
    create: true
    slug: "deck_project{{project-num}}"
    summary: '{{title}}(#{{project-num}})'
    description: >
      Please ensure that project numbers are sequential, with no gaps. 
      Currently, there is no way to safely remove a project. If you need to remove a project, either replace an existing project's content with a new one or contact Nathan for assistance.
    fields:
      - { label: "Project Number", name: "project-num", widget: "number", value_type: "int", min: 1 }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - label: "Gallery"
        name: "gallery"
        widget: "image"
        hint: "First image will be cover image."
        allow_multiple: true
        choose_url: true
        media_library:
          config:
            multiple: true
