
backend:
  name: git-gateway
  branch: master 

site_url: https://woodmancustomconstruction.netlify.app/

publish_mode: editorial_workflow
media_folder: "assets/work"
public_folder: "/assets/work"

collections:
  - name: "bathroom-project"
    label: "Bathroom Project"
    folder: "content"
    create: true
    slug: "bathroom_project{{project-num}}"
    summary: '{{title}}(#{{project-num}})'
    description: >
      Bahtroom projects. 
      Make sure there is no gap in project numbers below.
    fields:
      - { label: "Project Number", name: "project-num", widget: "number", value_type: "int", min: 1 }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - label: "Gallery"
        name: 'gallery'
        widget: 'image'
        choose_url: true
        media_library: 
        config: 
          multiple: true
          max_files: 999
  - name: "deck-project"
    label: "Deck Project"
    folder: "content"
    path: "project-deck/{{slug}}"
    create: true
    slug: "deck_project{{project-num}}"
    summary: '{{title}}(#{{project-num}})'
    description: >
      Deck projects. 
      Make sure there is no gap in project numbers below.
    fields:
      - { label: "Project Number", name: "project-num", widget: "number", value_type: "int", min: 1 }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Gallery", name: 'gallery', widget: 'image', choose_url: true, media_library: config: multiple: true, max_files: 999}

  - name: "cabinetry-project"
    label: "Cabinetry Project"
    folder: "content"
    path: "project-cabinetry/{{slug}}"
    create: true
    slug: "cabinetry_project{{project-num}}"
    summary: '{{title}}(#{{project-num}})'
    description: >
      Cabinetry projects. 
      Make sure there is no gap in project numbers below.
    fields:
      - { label: "Project Number", name: "project-num", widget: "number", value_type: "int", min: 1 }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Gallery", name: 'gallery', widget: 'image', choose_url: true, media_library: config: multiple: true, max_files: 999}

  - name: "fireplace-project"
    label: "Fireplace Project"
    folder: "content"
    path: "project-fireplace/{{slug}}"
    create: true
    slug: "fireplace_project{{project-num}}"
    summary: '{{title}}(#{{project-num}})'
    description: >
      Fireplace projects. 
      Make sure there is no gap in project numbers below.
    fields:
      - { label: "Project Number", name: "project-num", widget: "number", value_type: "int", min: 1 }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Gallery", name: 'gallery', widget: 'image', choose_url: true, media_library: config: multiple: true, max_files: 999}
